### ISSUE TITLE
Wrong size in BQ E4.5 Ubuntu Edition

### ISSUE THREAD

**Issue by costales** [goldenratio/xbmc-web-remote#17]
Hi! Thanks for this awesome app!

In the BQ E4.5 Ubuntu Edition phone, the screen is more bigger that the phone. Please, take a look to my picture.
![2015-02-14 10 42 02](https://cloud.githubusercontent.com/assets/5886786/6199231/4a1220c0-b437-11e4-96c6-baf75fd3df0a.jpg)

Thanks in advance!

**Comment by goldenratio** [comment]
Oops :) BTW is it the Ubuntu touch app or in the browser?

**Comment by costales** [comment]
Hi @goldenratio |o/
It's as native/webapp? application
It's this app: http://4.bp.blogspot.com/-D93CU9jz9Vc/VN8iRKeDsAI/AAAAAAAAEC4/z999DcrakVE/s1600/IMG_030.jpg
Thanks in advance!

**Comment by goldenratio** [comment]
ok, Thanks.
@costales  Btw can you do one more test. Can you open browser and enter this URL http://goldenratio.github.io/xbmc-web-remote/remote/remote.html and see if the layout is proper. Minimum width required is 320px, not sure why it is acting weird on BQ E4.5, layout even fits properly in Firefox Keon phone.

adding @elopio

**Comment by costales** [comment]
It's perfect in the web browser:
![2015-02-14 13 11 34](https://cloud.githubusercontent.com/assets/5886786/6199554/48170542-b44b-11e4-9c6b-6af342920b89.jpg)

**Comment by costales** [comment]
Uhm, I was reading this:
http://daker.me/2013/10/package-your-webapp-for-ubuntu-touch.html
"QtWebKit Webview is that the device-pixel-ratio (DPR) is not set automatically causing the content of the Webview to not scale correctly, so you'll need to get the corresponding value for your device from the QTWEBKIT_DPR environment variable, there is actually no way to read those variables using QML so you'll need to use some C++ code to read the QTWEBKIT_DPR and passe it to QML so the content of the WebView will scale accordingly"

Could it be a bug into the webapp library?

Best regards!

**Comment by goldenratio** [comment]
seems that bug is already fixed and released https://bugs.launchpad.net/webbrowser-app/+bug/1237348 (isn't it?)

not sure what is wrong, but you could try playing the source code /res/ubuntu_click contains the code.
I don't own Ubuntu device at the moment :) @elopio maintains the ubuntu app, we have to wait for him to reply.

**Comment by costales** [comment]
@goldenratio Thanks :) I don't know where to touch. It was installed from the Ubuntu Store with 1 click and the /res directory doesn't exist. 
Best regards!

**Comment by oSoMoN** [comment]
It appears the ubuntu HTML5 container on RTM still uses QtWebKit, hence the issue. In vivid it already uses Oxide and the app is rendered correctly (tested with the latest vivid-proposed image on my E4.5).
I’m told the update to Oxide will land shortly in RTM.

**Comment by goldenratio** [comment]
OK, thanks for the update. I will close the issue.

**Comment by costales** [comment]
Thanks a lot! :) I'll wait the update then.
Cheers!

**Comment by elopio** [comment]
![img_20150216_083756](https://cloud.githubusercontent.com/assets/617831/6213629/727239a2-b5b7-11e4-88a6-e2d8c686a48f.jpg)
Just to confirm what you are saying, here is how it looks on my bq on vivid. Thanks for the report and for digging into the problem.
