### ISSUE TITLE
Ubuntu Phone: Wrong seletected buttons

### ISSUE THREAD

**Issue by costales** [goldenratio/xbmc-web-remote#18]
Hi!

With the BQ Ubuntu Edition, the XBMC Remote (from Canonical) is connecting to the host fine, but it has this problem: Some clicks are doing a selected text (buttons) and it doesn't work anymore.

Please, see this video:
https://copy.com/JgdTnjbrJdP9fnVk

FYI: This URL in the browser is working perfect (appears to be the same):
http://goldenratio.github.io/xbmc-web-remote/remote/remote.html

Thanks in advance!

**Comment by goldenratio** [comment]
even in web browser, you are getting that selection UI?

**Comment by costales** [comment]
@goldenratio Not :) The browser works perfect. It's in the application.

**Comment by goldenratio** [comment]
good to hear it works perfect in web browser :)
I think Ubuntu's webview isn't perfect at the moment. I remember @elopio talking about this selection bug. https://github.com/goldenratio/xbmc-web-remote/pull/3#issuecomment-27172908

**Comment by costales** [comment]
I filled a bug in the webapps container then, Thanks a lot @goldenratio!!!
https://bugs.launchpad.net/webbrowser-app/+bug/1421982

**Comment by goldenratio** [comment]
I guess we can close this issue as well. Could be related to this..  https://github.com/goldenratio/xbmc-web-remote/issues/17#issuecomment-74486071
