### ISSUE TITLE
Kodi Port 9090 Listens on TCP6 only in Ubuntu 14.10 64bit

### ISSUE THREAD

**Issue by siuside** [goldenratio/xbmc-web-remote#19]
Hi 

So I have been reading that some of the users on Ubuntu 64bit are having problems connecting even if the allow remote control option is set in Services. I also had the same problem even after opening 9090 in Ubuntu Firewall. So this is what I saw in my box where for HTTP server I have manually chosen port 4040 (instead of the default 8080).

tifozi@tuxy:~$ netstat -an|grep 4040
tcp        0      0 0.0.0.0:4040            0.0.0.0:*               LISTEN
tcp6       0      0 :::4040                 :::*                    LISTEN
tifozi@tuxy:~$

But when I search for 9090 I get this

tifozi@tuxy:~$ netstat -an|grep 9090
tcp6       0      0 :::9090                 :::*                    LISTEN

Looks like port 9090 is not listening on TCP4. Could this be why some users are not able to connect even after opening it in firewall? Is this configurable?

**Comment by goldenratio** [comment]
Can you paste the screenshot of Kodi's remote settings screen.
Also make sure in remote settings you enable "allow program on other system
to control XBMC".

Also this could be completely Kodi issue.

**Comment by siuside** [comment]
Yup they are enabled as well as UPnP. This could be Kodi issue as well but bottom line is it is not listening on the TCP4 interface. As with all ports in my system, I enabled 9090 to be open in UFW as well.

**Comment by siuside** [comment]
netstat -anp |grep 9090
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::9090                 :::*                    LISTEN      12340/kodi.bin

**Comment by goldenratio** [comment]
found this, https://zaplanincan.wordpress.com/2015/02/14/kodi-network-ports/
seems 9090 is for TCP v6
But I guess this is not Kassi issue. Feel free to close this issue.

**Comment by siuside** [comment]
Indeed, what a bummer. I really liked the interface. I might open a ticket for the kodi team. Not sure.

Thanks VJ

**Comment by goldenratio** [comment]
But you could try tcp4 ports 1084, 1308, 1131 if it is open.

**Comment by siuside** [comment]
Tried it after opening ports 1353 1073 1289 (these are the tcp4 ports on my system after confirming through lsof) and it was a no go.
