### ISSUE TITLE
Support multiple media centers

### ISSUE THREAD

**Issue by goldenratio** [goldenratio/xbmc-web-remote#24]
In settings page, add feature to add more than one media center.

**Comment by goldenratio** [comment]
![image](https://cloud.githubusercontent.com/assets/3019293/10410897/8a2fbe14-6f59-11e5-8e71-499094bf4505.png)

![image](https://cloud.githubusercontent.com/assets/3019293/10410899/994afdaa-6f59-11e5-8fd9-8811e22091d7.png)

**Comment by goldenratio** [comment]
Demo: http://goldenratio.github.io/xbmc-web-remote/remote/remote.html

**Comment by goldenratio** [comment]
![image](https://cloud.githubusercontent.com/assets/3019293/10415960/dba0bc16-7009-11e5-86b4-614075a9254b.png)

**Comment by stevedowling** [comment]
But how do you actually add a new connection? I see the drop down but I can only change the existing connection, not add a new one.

**Comment by goldenratio** [comment]
Just give a different name for Display name and click connect.

Once connection is success, it will appear in dropdown.

**Comment by stevedowling** [comment]
When I do that, the other connection goes away.

**Comment by goldenratio** [comment]
Clear the display name and click on the arrow.

**Comment by stevedowling** [comment]
That works. Cheers. Not the most intuitive though :)

**Comment by goldenratio** [comment]
Agree :)
