### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Sanjjay** [goldenratio/xbmc-web-remote#26]
Please could you add support for arrow keys to skip forward and back when playing a video.

Also if the keyboard keymap from Kodi can be added to this app would be great.

Hope to hear from you.

Thanks

**Comment by goldenratio** [comment]
> Please could you add support for arrow keys to skip forward and back when playing a video.

Already supported, use Ctrl + right arrow and Ctrl + left arrow

> Also if the keyboard keymap from Kodi can be added to this app would be great.

Most of the keyboard shortcuts are supported. Also you can rollover on the buttons in the remote to get the shortcut key.

**Comment by Sanjjay** [comment]
Thank you for the quick reply.

I am using the windows desktop remote zip file, rolling over on the buttons doesn't bring anything up.

Just curious can the remote be programed without pressing the Ctrl button and just pressing arrows.

Also while playing a video clicking with mouse on the arrow keys "left, right, up, and down"  in the remote to skip forward and back would be great if can be added.

Couldn't work out the below keys for Kodi :-

Power Menu Letter S
Subtitle  Enable/Disable  Letter T
Forward 10 min Arrow up.
Back 10 min Arrow Down.
Aspect Ratio Letter Z
Audio Offset Letter A
Subtitle Offset Letter Q (I have assigned this in my own custom keymap as nothing was assigned to Letter Q).

**Comment by goldenratio** [comment]
Closing this.. No progress or solution.
