### ISSUE TITLE
Don't shutdown the computer without notice

### ISSUE THREAD

**Issue by llucax** [goldenratio/xbmc-web-remote#27]
Hi, I just installed this very nice addon but had a nasty surprise. When I clicked on the off button, my whole computer shut down (which is not a dedicated media server, is a multifunction home server, so shutting down is **bad**). What I expected was just for Kodi to exit.

I think there should be at least a one time warning about this, and ideally a submenu to pick what to do (like in Kodi itself and in Kore, the official Android remote control). If that's too complicated, maybe there could be a setting to choose what to do when the off button is clicked, or at least an option to hide that button (for me is really to risky to use this addon, I can't afford to press the off button accidentally).

Thanks!

**Comment by goldenratio** [comment]
sorry for the nasty surprise :)
I added shutdown menu... 
![image](https://cloud.githubusercontent.com/assets/3019293/8765081/8d01fc38-2e04-11e5-846c-4de5a1187186.png)


look for version 2.3.1

**Comment by llucax** [comment]
Sweet! Thanks for the quick  answer and fix! Is it possible to add the 2 other options present in Kodi and Kore: Quit and Suspend?

**Comment by goldenratio** [comment]
what does "Quit" do?

**Comment by llucax** [comment]
Just quit Kodi, same as if you go to the shutdown menu in Kodi itself and select Quit. Well, I just checked and Kodi calls it "Exit". There is also a "Power off system", "Custom shutdown time", "Reboot" and "Inhibit idle shutdown". Kore's menu as: Quit, Suspend, Reboot and Shutdown (and  actually a Wake up too). So they are not as consistent as I thought. I only use Quit/Exit to be honest :)

**Comment by goldenratio** [comment]
ok added..
![image](https://cloud.githubusercontent.com/assets/3019293/8765248/982ae702-2e0c-11e5-9c21-0835c2fd7d98.png)

**Comment by llucax** [comment]
:boom: Thanks!
