### ISSUE TITLE
Keyboard shortcut for "send text"?

### ISSUE THREAD

**Issue by nunofgs** [goldenratio/xbmc-web-remote#29]
When in the "send text" screen, is there a keyboard shortcut to submit your text?

**Comment by goldenratio** [comment]
no, I will add it to the next release.
I guess, "Enter" key will do the job.

**Comment by nunofgs** [comment]
Thanks, "Enter" sounds perfect! By the way, in my opinion, it should also dismiss the "send text" screen when pressing enter.

**Comment by goldenratio** [comment]
fixed http://goldenratio.github.io/xbmc-web-remote/remote/remote.html
Soon will make a release in Chrome store
