### ISSUE TITLE
The ability to add multiple devices (Kodis) in the extension's settings.

### ISSUE THREAD

**Issue by Zvezke** [goldenratio/xbmc-web-remote#35]
I really like this extension. I use it a lot.

One feature I'm missing, though, is being able to add multiple devices in the settings: I have Kodi both in my living room and in my bedroom, and every time change room, I have to change the ip-adr. in the extension's settings. It would be really nice to be able to have multiple devices – and maybe even name them in the settings.

I'd really appreciate the feature.

**Comment by goldenratio** [comment]
Hi,
Thanks for the feedback. We already have enhancement request https://github.com/goldenratio/xbmc-web-remote/issues/24 
I will find time to finish this. Closing this now.

**Comment by goldenratio** [comment]
made some progress here, https://github.com/goldenratio/xbmc-web-remote/issues/24
