### ISSUE TITLE
Not working, FF Quantum Beta

### ISSUE THREAD

**Issue by jrubenc** [goldenratio/xbmc-web-remote#43]
Hi,

As per issue #42 I'm running FF 57.0b4. Does not work.

The extension is downloaded directly from https://addons.mozilla.org/en-US/firefox/addon/xbmc-remote-control/ and it's the only installed extension.

Handshake attempt from FF:

T 2017/09/30 00:41:06.544015 192.168.1.15:61421 -> 192.168.1.35:9090 [AP]
  GET /jsonrpc HTTP/1.1..Host: 192.168.1.35:9090..User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0..Accept: text/html,application/xhtml
  +xml,application/xml;q=0.9,*/*;q=0.8..Accept-Language: en-US,en;q=0.5..Accept-Encoding: gzip, deflate..Sec-WebSocket-Version: 13..Origin: moz-extension://c8ab1884-6342-4603-ac
  05-05a6793ee04d..Sec-WebSocket-Extensions: permessage-deflate..Sec-WebSocket-Key: psikuW8BbOqEo4ha1Js6Dg==..Connection: keep-alive, Upgrade..Pragma: no-cache..Cache-Control: n
  o-cache..Upgrade: websocket

No reply from Kodi (Krypton 17.4)

And this is the handshake under Chrome:

#
T 2017/09/30 00:44:13.434947 192.168.1.15:61518 -> 192.168.1.35:9090 [AP]
  GET /jsonrpc HTTP/1.1..Host: 192.168.1.35:9090..Connection: Upgrade..Pragma: no-cache..Cache-Control: no-cache..Upgrade: websocket..Origin: chrome-extension://jgannjdjlpnoibph
  pbmmfjkejcfhcmjp..Sec-WebSocket-Version: 13..User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36..A
  ccept-Encoding: gzip, deflate..Accept-Language: es,en-US;q=0.8,en;q=0.6..Sec-WebSocket-Key: qgCAiKdiSKAPaI6boOVN0w==..Sec-WebSocket-Extensions: permessage-deflate; client_max_
  window_bits....                                                                                                                                                                
##
T 2017/09/30 00:44:13.435472 192.168.1.35:9090 -> 192.168.1.15:61518 [AP]
  HTTP/1.1 101 Switching Protocols..Upgrade: websocket..Connection: Upgrade..Sec-WebSocket-Accept: Y/gyhUQHzcKEIbM6zdzFpcr4q0s=....                                              
#

Thanks,

Rubén.

**Comment by goldenratio** [comment]
Unable to reproduce.
